name: PocketMoney
main: PocketMoney\PocketMoney
version: 3.2
api: [1.10.0]
load: POSTWORLD
author: MinecrafterJPN
authors: [MinecrafterJPN]
description: "PocketMoney is the foundation of money system for PocketMine"
website: "https://github.com/MinecrafterJPN/PocketMoney"
commands:
 money:
  description: "PocketMoney command"
  usage: "Usage: /money [subcommand]\nRefer to /money help"
  permission: money.command
permissions:
 money:
  default: op
  description: "Allows using all the PocketMoney things"
  children:
   money.command:
    default: true
    description: "Allows using all the PocketMoney commands"
    children:
     money.command.view:
      default: true
      description: "Allows using /money view commands"
     money.command.pay:
      default: true
      description: "Allows using /money pay commands"
     money.command.withdraw:
      default: true
      description: "Allows using /money withdraw commands"
     money.command.create:
      default: true
      description: "Allows using /money create commands"
     money.command.hide:
      default: true
      description: "Allows using /money hide commands"
     money.command.unhide:
      default: true
      description: "Allows using /money unhide commands"
     money.command.top:
      default: true
      description: "Allows using /money top commands"
     money.command.stat:
      default: true
      description: "Allows using /money stat commands"